name       : aegisub
version    : 3.2.2
release    : 16
source     :
    - http://ftp.aegisub.org/pub/archives/releases/source/aegisub-3.2.2.tar.xz : c55e33945b82d8513c02ea6e782f0d72c726adcd3707e95b8c0022f6151e6885
license    :
    - BSD-3-Clause
    - MIT
    - MPL-1.1
component  : multimedia.video
summary    : Aegisub is a free, cross-platform open source tool for creating and modifying
    subtitles
description: |
    Aegisub is a free, cross-platform open source tool for creating and modifying subtitles
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(ffms2)
    - pkgconfig(fftw3)
    - pkgconfig(fontconfig)
    - pkgconfig(gl)
    - pkgconfig(hunspell)
    - pkgconfig(ice)
    - pkgconfig(libass)
    - pkgconfig(libpulse)
    - pkgconfig(icu-i18n)
    - pkgconfig(openal)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(x11)
    - libboost-devel
    - libiconv-devel
    - wxwidgets-devel
    - yasm
setup      : |
    # http://site.icu-project.org/download/61#TOC-Migration-Issues
    export CPPFLAGS+=' -DU_USING_ICU_NAMESPACE=1'

    %patch -p1 < $pkgfiles/fix-compliation-against-icu-59.1.patch

    %reconfigure
build      : |
    %make
install    : |
    %make_install
