name       : aegisub
version    : 3.3.2
release    : 29
source     :
    - https://github.com/wangqr/Aegisub/archive/d771fb21af9db95fb174c95549fc765ef39652cd.tar.gz : 814d198ecc9efdcc6c3ed0faf25f70746b2b90c6ae103986f3bb8ea6de469b6c
license    :
    - BSD-3-Clause
    - MIT
    - MPL-1.1
component  : multimedia.video
summary    : Cross-platform advanced subtitle editor
description: |
    Aegisub is a free, cross-platform open source tool for creating and modifying subtitles. Aegisub makes it quick and easy to time subtitles to audio, and features many powerful tools for styling them, including a built-in real-time video preview.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(ffms2)
    - pkgconfig(fftw3)
    - pkgconfig(gl)
    - pkgconfig(hunspell)
    - pkgconfig(icu-i18n)
    - pkgconfig(libass)
    - pkgconfig(libpulse)
    - pkgconfig(luajit)
    - pkgconfig(uchardet)
    - pkgconfig(x11)
    - libboost-devel
    - wxwidgets-devel
environment: |
    export FORCE_GIT_VERSION=$version
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
